#!/bin/bash
# asu (AWS Switch User)

set -e

exportnull(){
    export -n AWS_ACCESS_KEY_ID
    export -n AWS_SECRET_ACCESS_KEY
    export -n AWS_SESSION_TOKEN
    export -n AWS_DEFAULT_PROFILE
    export -n AWS_DEFAULT_REGION
    export -n AWS_DEFAULT_OUTPUT
    export -n AWS_SHARED_CREDENTIALS_FILE
    export -n AWS_CONFIG_FILE
}

while getopts en OPT
do
  case $OPT in
    "e" ) FLG_SET_ENV="TRUE" ;;
    "n" ) FLG_NULL="TRUE" ;;
  esac
done

if [ "$FLG_NULL" = "TRUE" ]; then
  exportnull
  exit 0
fi

shift `expr $OPTIND - 1`
if [ $# -le 1 ]; then
  echo "Error: no user." 1>&2
  exit 1
fi
user=$1

exportnull
ln -f ~/.aws/${user}.config ~/.aws/config
ln -f ~/.aws/${user}.credentials ~/.aws/credentials

aws configure list
