#!/bin/bash
# asu (AWS   User)

set -e

echoconfig(){
    aws configure list
    echo -e "\nEnvironment variables"
    echo "---------------------"
    echo "AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}"
    echo "AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}"
    echo "AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN}"
    echo "AWS_DEFAULT_PROFILE: ${AWS_DEFAULT_PROFILE}"
    echo "AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}" 
    echo "AWS_DEFAULT_OUTPUT: ${AWS_DEFAULT_OUTPUT}"
    echo "AWS_SHARED_CREDENTIALS_FILE: ${AWS_DEFAULT_OUTPUT}"
    echo "AWS_CONFIG_FILE: ${AWS_DEFAULT_OUTPUT}"
}

while getopts en OPT
do
  case $OPT in
    "n" ) FLG_NULL="TRUE" ;;
  esac
done

if [ "$FLG_NULL" = "TRUE" ]; then
  rm -f ~/.aws/config
  rm -f ~/.aws/credentials
  echoconfig
  exit 0
fi

if [ $# -eq 0 ]; then
  echoconfig
  exit 0
fi

user=$1
echo -e "Info: substitute user to ${user}\n"

ln -f ~/.aws/${user}.config ~/.aws/config
ln -f ~/.aws/${user}.credentials ~/.aws/credentials
echoconfig
